Update patch set 2
Patch Set 2:

It looks like this is the error (buried 4 links deep, in a zip file):

  File "/tmp/Soong.python_shveE1/test_adb.py", line 300
    ["adb", "-L", f"tcp:[::1]:{server_port}", "server"],
                                           ^
SyntaxError: invalid syntax

Apparently, "use python3" means "use whatever version of python3 is on the host", and some (all?) of our build servers have a version older than 3.6, so the format string syntax isn't available.

Patch-set: 2
CC: Gerrit User 1074628 <1074628@85c56323-6fa9-3386-8a01-6480fb634889>
Reviewer: Gerrit User 1079148 <1079148@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Presubmit-Ready=0