Update patch set 5
Patch Set 5: Verified+1 Presubmit-Ready+1

> Patch Set 4: Verified-1
> 
> This version failed to build pass w/ following error:
> 
>   2020-05-28 09:48:29 - build_image.py - ERROR   : Failed to build out/target/product/walleye/vendor.img from out/target/product/walleye/vendor
>   ...
>   ValueError: The header said we should have 125961 output blocks, but we saw 84360
> 
> (Full log: https://android-build.googleplex.com/builds/pending/P14694022/walleye-userdebug)
> 
> I will update again once it's fixed.

The previous build failure is because the 'write_all_blocks' starts after sparse file header - including chunk count - is written. So if we split large chunks after that, the header and body of the sparse file will be inconsistent.

This is fixed in the latest patchset, by splitting the chunks before writing the header.

Patch-set: 5
Reviewer: Gerrit User 1345812 <1345812@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Verified=+1
Label: Presubmit-Ready=+1