Update patch set 1
Patch Set 1:

marlin results:

$ system/core/bootstat/boot_reason_test.sh optional_rescueparty
INFO: selected test(s): optional_rescueparty

[ RUN      ] optional_rescueparty 
INFO: expected duration of 'optional_rescueparty' test ~45 seconds
INFO: ok "reboot" for Android property ro.boot.bootreason
INFO: ok "reboot,rescueparty" for Android property sys.boot.reason
INFO: ok "reboot,rescueparty" for Android property persist.sys.boot.reason
WARNING: legacy devices are allowed to fail following ro.boot.bootreason result
ERROR: expected "reboot,rescueparty" got "reboot"
       for Android property ro.boot.bootreason
INFO: 'rescueparty' test duration 55 seconds
[  FAILED  ] rescueparty 

[  FAILED  ] optional_rescueparty

NB: and just noticed that the rename of TEST caused confusion, expect respin shortly to not rename.

Patch-set: 1
Reviewer: Mark Salyzyn <1032276@85c56323-6fa9-3386-8a01-6480fb634889>