Update patch set 1
Patch Set 1: Verified+1 Presubmit-Ready+1

PTAL

As mentioned in the previous commit, if we try to connect to an already-connected device AND there's a device already connected through USB, it fails with

 error: more than one device/emulator

since the smartsocket will attempt to find a transport before it is setup. I'm not 100% sure I'm introducing this regression, though. Only maybe making it worse / consistent. I'm also happy to help fix that issue if you point me in the right direction.

Patch-set: 1
Reviewer: Luis Hector Chavez <1066743@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Verified=+1
Label: Presubmit-Ready=+1