Update patch set 2
Patch Set 2:

system/core/libziparchive/zip_writer.cc:361:3: error: use of overloaded operator '<<' is ambiguous (with operand types 'basic_ostream<char, std::__1::char_traits<char> >' and 'nullptr_t')
  CHECK_NE(z_stream_->next_out, nullptr);


Moving to CHECK_EQ is definitely not worth it. But now I can't upload my old patch set...

Patch-set: 2
Reviewer: Adam Lesinski <1043034@85c56323-6fa9-3386-8a01-6480fb634889>